download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-docker-3.4.0.tar.gz
format_version: 1.0.0
name: docker
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.4.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/docker/versions/3.4.0/
