download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cloud-common-2.1.1.tar.gz
format_version: 1.0.0
name: common
namespace: cloud
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.1.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/cloud/common/versions/2.1.1/
